name: CI/CD

on:
  push:
    branches:
      - ci-pipeline
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Dependencies
        run: mvn clean install

      - name: Run Unit and Integration Tests
        run: mvn test

      - name: Static Code Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=esn8der_tour-of-heroes-api
      
      - run: cat ~/.m2/settings.xml

      - name: Modificar settings.xml
        run: |
          echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                                    https://maven.apache.org/xsd/settings-1.0.0.xsd">
          <servers>
              <server>
                  <id>Practica1</id>
                  <username>ProyectoIntegrador2-UdeA</username>
                  <password>${AZURE_ARTIFACTS_TOKEN}</password>
              </server>
          </servers>
          </settings>' > ~/.m2/settings.xml
        env:
          AZURE_ARTIFACTS_TOKEN: ${{ secrets.AZURE_ARTIFACTS_TOKEN }}

      - name: Publish Artifact to Azure Artifacts
        run: mvn deploy

      - name: Save Artifact in GitHub Actions
        run: |
          mkdir artifacts
          cp target/tour-hero-api-1.0-SNAPSHOT.war artifacts/tour-hero-api-1.0-SNAPSHOT.war
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact to GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: tour-hero-api
          path: artifacts/tour-hero-api-1.0-SNAPSHOT.war
