name: CI/CD

on:
  push:
    branches:
      - ci-pipeline
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build, Test, and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: Practica1
          server-username: ProyectoIntegrador2-UdeA
          server-password: AZURE_TOKEN  # Utiliza la variable de entorno AZURE_TOKEN

      - name: Install Dependencies
        run: mvn --batch-mode install

      - name: Compile the project
        run: mvn --batch-mode compile

      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          AZURE_TOKEN: ${{ secrets.AZURE_ARTIFACTS_TOKEN }}

      - name: Execute Unit Tests
        run: mvn --batch-mode test

      # - name: Execute Integration Tests
      #   # Add your integration test command here

      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=esn8der_tour-of-heroes-api

      # - name: Quality Gates Evaluation
      #   # Add your quality gates evaluation command here

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: tour-of-hero-artifact  # Nombre de tu artefacto
          path: target/*.war  # Ruta al archivo .war o patrón de búsqueda