name: CI/CD

on:
  push:
    branches:
      - ci-pipeline
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Install Dependencies
        run: mvn clean install

      - name: Run Unit and Integration Tests
        run: mvn test

      - name: Static Code Analysis
        run: mvn sonar:sonar -Dsonar.projectKey=esn8der_tour-of-heroes-api

      - name: Publish Artifact to Azure Artifacts
        run: mvn deploy

      - name: Save Artifact in GitHub Actions
        run: |
          mkdir artifacts
          cp target/tour-hero-api-1.0-SNAPSHOT.war artifacts/tour-hero-api-1.0-SNAPSHOT.war
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact to GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: tour-hero-api
          path: artifacts/tour-hero-api-1.0-SNAPSHOT.war
