name: CI/CD

on:
  push:
    branches:
      - ci-pipeline
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: Practica1
          server-username: ProyectoIntegrador2-UdeA
          server-password: AZURE_TOKEN
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          AZURE_TOKEN: ${{ secrets.AZURE_ARTIFACTS_TOKEN }}

      # - name: Cache Maven packages
      #   uses: actions/cache@v3
      #   with:
      #     path: ~/.m2
      #     key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
      #     restore-keys: ${{ runner.os }}-m2

      # - name: Install Dependencies
      #   run: mvn clean install

      # - name: Run Unit and Integration Tests
      #   run: mvn test

      # # - name: Static Code Analysis
      # #   run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=esn8der_tour-of-heroes-api

      # - name: Publish to Repositories
      #   run: mvn --batch-mode deploy
       
